//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KeyboardControl
{
    [Serializable]
    public class Raspimouse_poseMsg : Message
    {
        public const string k_RosMessageName = "keyboard_control/raspimouse_pose";
        public override string RosMessageName => k_RosMessageName;

        //  Position and orientation of RasPiMouse
        public double x;
        public double y;
        public double z;
        public double rotation_x;
        public double rotation_y;
        public double rotation_z;
        public double timestamp;

        public Raspimouse_poseMsg()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.rotation_x = 0.0;
            this.rotation_y = 0.0;
            this.rotation_z = 0.0;
            this.timestamp = 0.0;
        }

        public Raspimouse_poseMsg(double x, double y, double z, double rotation_x, double rotation_y, double rotation_z, double timestamp)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.rotation_x = rotation_x;
            this.rotation_y = rotation_y;
            this.rotation_z = rotation_z;
            this.timestamp = timestamp;
        }

        public static Raspimouse_poseMsg Deserialize(MessageDeserializer deserializer) => new Raspimouse_poseMsg(deserializer);

        private Raspimouse_poseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.rotation_x);
            deserializer.Read(out this.rotation_y);
            deserializer.Read(out this.rotation_z);
            deserializer.Read(out this.timestamp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.rotation_x);
            serializer.Write(this.rotation_y);
            serializer.Write(this.rotation_z);
            serializer.Write(this.timestamp);
        }

        public override string ToString()
        {
            return "Raspimouse_poseMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nrotation_x: " + rotation_x.ToString() +
            "\nrotation_y: " + rotation_y.ToString() +
            "\nrotation_z: " + rotation_z.ToString() +
            "\ntimestamp: " + timestamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
